# Generate https://... links by default
PREFERRED_URL_SCHEME: https

# Set to false to prevent users from running arbitrary code
DEBUG: False

# Don't sort JSON dictionaries
JSON_SORT_KEYS: False

# UA to be used by
# CUSTOM_UA: "wiki-topic (toolforge) -- <your-email-address>"